# Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

# Loading Datasets from sklearn

In [2]:
from sklearn.datasets import load_wine
wine=load_wine()
print(wine.data)
print(wine.target)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [3]:
print(wine.data.shape)
print(wine.target.shape)

(178L, 13L)
(178L,)


In [4]:
x=wine.data
y=wine.target

In [5]:
from sklearn .preprocessing import StandardScaler as SS

In [7]:
scaler=SS()
X=scaler.fit_transform(x)

In [8]:
X.shape

(178L, 13L)

In [9]:
# Question 3
from sklearn.model_selection import train_test_split as tts
train_x,test_x,train_y,test_y=tts(X,y,test_size=0.2)

In [10]:
# Question 4 Perform PCA
from sklearn.decomposition import PCA
pca_10=PCA(n_components=10)
X=pca_10.fit_transform(X)
X.shape

(178L, 10L)

In [11]:
# Question 6
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(train_x,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
pred=model.predict(test_x)
results=pd.DataFrame({'Actual':test_y,'Predicted':pred})
results

Actual  Predicted
0        1          1
1        0          0
2        1          1
3        0          0
4        2          2
5        2          2
6        1          1
7        2          2
8        1          1
9        1          1
10       0          0
11       1          1
12       1          1
13       0          0
14       0          0
15       1          1
16       0          0
17       2          2
18       2          2
19       0          0
20       2          2
21       0          0
22       1          1
23       0          0
24       1          1
25       0          0
26       0          0
27       1          1
28       2          2
29       2          2
30       1          1
31       0          0
32       2          2
33       0          0
34       2          2
35       1          2

In [13]:
from sklearn.metrics import classification_report as cr, confusion_matrix as cm, accuracy_score as ac

# Classification report

In [15]:
print(cr(test_y,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       1.00      0.92      0.96        13
          2       0.91      1.00      0.95        10

avg / total       0.97      0.97      0.97        36



# confusion matrix

In [16]:
print(cm(test_y,pred))

[[13  0  0]
 [ 0 12  1]
 [ 0  0 10]]


# Accuracy score

In [17]:
print(ac(test_y,pred)*100)

97.22222222222221
